# Generated by Django 3.2 on 2021-04-24 10:00

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('tasks', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='task',
            old_name='created_date',
            new_name='date_created',
        ),
    ]
